### ISSUE TITLE
Double div parente pas nécessaire

### ISSUE THREAD

**Issue by PaulineWildTeacher** [SergeyGoesWild/DreamDeck#6]
![image](https://github.com/SergeyGoesWild/DreamDeck/assets/154433634/f5bf876a-190e-43e5-a764-126f278ca0de)
Tu as ici une div sans class, qui entoure une div avec la className deck-section. Si tu as deux div imbriquée de la sorte, dont une sans className et qu'elles ont très exactement le même "contenu" c'est que la première div parente ne te sert à rien.
Mieux vaux éviter de surcharger le DOM de div inutiles. Tu peux donc supprimer les lignes 4 et 13 de la capture d'écran

**Comment by PaulineWildTeacher** [comment]
![image](https://github.com/SergeyGoesWild/DreamDeck/assets/154433634/71ecb653-8537-4285-915d-1eef253f1e5d)
Même problème : tu peux supprimer la ligne 10 et la ligne 22

**Comment by espinovincent** [comment]
solved
